### ISSUE TITLE
Vanilla's flavors tasks list

### ISSUE THREAD

**Issue by mirkobrombin** [Vanilla-OS/iso-builder#113]
There are 2 new versions of Vanilla OS planned: Core and KDE.

> This post is only a reference to a future project. There are no promises.

### Core
This provide the base system (ABRoot + Apx + VSO + vanilla-base-meta). It came with no desktop environment and can be used as a base for other flavors.

#### Tasks
- [x] remove desktop stuff from [vanilla-base-meta](https://github.com/Vanilla-OS/vanilla-base-meta)
- [ ] ensure core apps (ABRoot, Apx and VSO) does not depends on GUI applications
- [ ] build Vanilla OS Core ISO

#### Common
- [ ] write flavor's guidelines

#### KDE
- [ ] Vanilla OS Core ready
- [ ] make Calamares supports ABRoot post-install
- [ ] rewrite Vanilla apps in Qt (First Setup, Vanilla Control Center and Upgrade Utility)
- [ ] build Vanilla OS KDE ISO

**Comment by ghost** [comment]
> rewrite Vanilla apps in Qt (First Setup, Vanilla Control Center and Upgrade Utility)

The latest KDE Plasma (5.27) released with a [welcome app](https://invent.kde.org/plasma/plasma-welcome) which can be extended with custom pages so creating a whole new First Setup app in Qt does not make sense anymore.

The functionality of Vanilla Control Center could be implemented as a KCM instead of an app, so it could be integrated into KDE System Settings as any other page.

**Comment by mirkobrombin** [comment]
This is good

**Comment by ghost** [comment]
I started working on custom pages for plasma-welcome: https://github.com/dogyx/vanilla-kde-welcome-pages

**Comment by mirkobrombin** [comment]
Oh, looks good. Nice work!

**Comment by mizzunet** [comment]
Would you add support for installation into btrfs subvolumes? Perhaps, it could be possible with the to be relased Core.

It would be wonderful it the GUI installers supported this. I suppose Fedora's Anaconda installer have it.

**Comment by mirkobrombin** [comment]
There are some news in our latest article: https://vanillaos.org/blog/article/2023-02-03/vanilla-os-core---a-minimal-and-clean-base

**Comment by nonetrix** [comment]
Rust based Cosmic isn't out yet, but what does everyone think of a Cosmic flavor in the future? Cosmic seems to be everything I personally want in a desktop, it supports both tiling and floating as first class citizens, it is very customizable, it is a desktop environment not a window manager so not messing with config files, etc.
